# Generated by Django 4.0.4 on 2022-05-07 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dinastia', '0003_staffs_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('patronymic', models.CharField(max_length=200)),
                ('phone', models.IntegerField(max_length=10)),
                ('dob', models.DateField()),
            ],
        ),
    ]
