# Generated by Django 4.0.4 on 2022-05-07 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dinastia', '0004_patients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
