# Generated by Django 4.0.4 on 2022-05-07 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dinastia', '0005_alter_patients_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inspections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('complaints', models.TextField()),
                ('anamnesis', models.TextField()),
                ('diagnosis', models.TextField()),
                ('additionally', models.TextField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dinastia.patients')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dinastia.staffs')),
            ],
        ),
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dinastia.inspections')),
            ],
        ),
    ]
