# Generated by Django 4.0.4 on 2022-05-07 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dinastia', '0006_inspections_files'),
    ]

    operations = [
        migrations.CreateModel(
            name='InspectionsTemplates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(max_length=200)),
                ('complaints', models.TextField()),
                ('anamnesis', models.TextField()),
                ('diagnosis', models.TextField()),
                ('additionally', models.TextField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dinastia.departments')),
            ],
        ),
    ]
