# Generated by Django 4.0.4 on 2022-05-08 14:34

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('dinastia', '0009_alter_inspections_additionally_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspectionstemplates',
            name='additionally',
            field=tinymce.models.HTMLField(verbose_name='Дополнительно'),
        ),
        migrations.AlterField(
            model_name='inspectionstemplates',
            name='anamnesis',
            field=tinymce.models.HTMLField(verbose_name='Анамнез'),
        ),
        migrations.AlterField(
            model_name='inspectionstemplates',
            name='complaints',
            field=tinymce.models.HTMLField(verbose_name='Жалобы'),
        ),
        migrations.AlterField(
            model_name='inspectionstemplates',
            name='diagnosis',
            field=tinymce.models.HTMLField(verbose_name='Диагноз'),
        ),
        migrations.AlterField(
            model_name='inspectionstemplates',
            name='template_name',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='patients',
            name='dob',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='patients',
            name='phone',
            field=models.IntegerField(null=True),
        ),
    ]
