# Generated by Django 4.0.4 on 2022-05-08 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dinastia', '0010_alter_inspectionstemplates_additionally_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspections',
            name='staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dinastia.staffs', verbose_name='Сотрудник'),
        ),
    ]
