# Generated by Django 4.0.4 on 2022-05-08 15:06

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('dinastia', '0011_alter_inspections_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspections',
            name='additionally',
            field=tinymce.models.HTMLField(null=True, verbose_name='Дополнительно'),
        ),
        migrations.AlterField(
            model_name='inspections',
            name='anamnesis',
            field=tinymce.models.HTMLField(null=True, verbose_name='Анамнез'),
        ),
        migrations.AlterField(
            model_name='inspections',
            name='complaints',
            field=tinymce.models.HTMLField(null=True, verbose_name='Жалобы'),
        ),
        migrations.AlterField(
            model_name='inspections',
            name='diagnosis',
            field=tinymce.models.HTMLField(null=True, verbose_name='Диагноз'),
        ),
        migrations.AlterField(
            model_name='inspectionstemplates',
            name='additionally',
            field=tinymce.models.HTMLField(null=True, verbose_name='Дополнительно'),
        ),
        migrations.AlterField(
            model_name='inspectionstemplates',
            name='anamnesis',
            field=tinymce.models.HTMLField(null=True, verbose_name='Анамнез'),
        ),
        migrations.AlterField(
            model_name='inspectionstemplates',
            name='complaints',
            field=tinymce.models.HTMLField(null=True, verbose_name='Жалобы'),
        ),
        migrations.AlterField(
            model_name='inspectionstemplates',
            name='diagnosis',
            field=tinymce.models.HTMLField(null=True, verbose_name='Диагноз'),
        ),
    ]
