# Generated by Django 4.0.4 on 2022-05-08 15:14

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('dinastia', '0012_alter_inspections_additionally_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspections',
            name='additionally',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Дополнительно'),
        ),
        migrations.AlterField(
            model_name='inspections',
            name='anamnesis',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Анамнез'),
        ),
        migrations.AlterField(
            model_name='inspections',
            name='complaints',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Жалобы'),
        ),
        migrations.AlterField(
            model_name='inspections',
            name='diagnosis',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Диагноз'),
        ),
        migrations.AlterField(
            model_name='inspectionstemplates',
            name='additionally',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Дополнительно'),
        ),
        migrations.AlterField(
            model_name='inspectionstemplates',
            name='anamnesis',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Анамнез'),
        ),
        migrations.AlterField(
            model_name='inspectionstemplates',
            name='complaints',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Жалобы'),
        ),
        migrations.AlterField(
            model_name='inspectionstemplates',
            name='diagnosis',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Диагноз'),
        ),
    ]
