# Generated by Django 4.0.4 on 2022-05-15 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dinastia', '0013_alter_inspections_additionally_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='files',
            name='url',
        ),
        migrations.AddField(
            model_name='files',
            name='file',
            field=models.FileField(default='-', upload_to='files/inspections'),
        ),
        migrations.AlterField(
            model_name='files',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='inspectionstemplates',
            name='department',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dinastia.departments'),
        ),
        migrations.AlterField(
            model_name='patients',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patients',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
