# Generated by Django 4.0.4 on 2022-05-21 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dinastia', '0015_alter_users_managers_users_date_joined_users_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='files',
            name='inspection',
        ),
        migrations.AddField(
            model_name='files',
            name='patient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dinastia.patients'),
        ),
        migrations.AlterField(
            model_name='inspectionstemplates',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dinastia.departments'),
        ),
    ]
