# Generated by Django 4.0.4 on 2022-05-21 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dinastia', '0017_alter_files_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='phone',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
