# Generated by Django 4.0.4 on 2022-05-28 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dinastia', '0018_alter_patients_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='patients',
            name='contact_persan',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='patients',
            name='contact_persan_phone',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patients',
            name='reg_address',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='patients',
            name='sex',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='patients',
            name='snils',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='patients',
            name='stable_address',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='patients',
            name='phone',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
