# Generated by Django 4.0.4 on 2022-05-28 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dinastia', '0020_rename_stable_address_patients_permanent_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patients',
            old_name='contact_persan',
            new_name='contact_person',
        ),
        migrations.RenameField(
            model_name='patients',
            old_name='contact_persan_phone',
            new_name='contact_person_phone',
        ),
    ]
