# Generated by Django 4.0.4 on 2022-09-02 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dinastia', '0022_alter_patients_contact_person_alter_patients_dob_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=200, verbose_name='Код')),
                ('name', models.CharField(max_length=200, verbose_name='Наименование')),
                ('price', models.FloatField(verbose_name='Цена')),
                ('conditional_unit_of_labor', models.FloatField(verbose_name='УЕТ')),
                ('external', models.BooleanField(verbose_name='Внешняя услуга')),
            ],
        ),
    ]
