# Generated by Django 4.0.4 on 2022-09-02 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dinastia', '0023_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='external',
            field=models.BooleanField(default=False, verbose_name='Внешняя услуга'),
        ),
    ]
