# Generated by Django 4.0.4 on 2022-09-03 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dinastia', '0025_servicecategories_services_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashReceipts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Наименование')),
            ],
        ),
    ]
