# Generated by Django 4.0.4 on 2022-09-19 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dinastia', '0027_expenses'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Активно'),
        ),
    ]
